version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${PGHOST}
      DB_PORT: ${PGPORT}
      DB_USER: ${PGUSER}
      DB_PASSWORD: ${PGPASSWORD}
      DB_NAME: ${PGDATABASE}
      PORT: 8080
      SECRET_KEY: ${SECRET_KEY}
